#!/usr/bin/env python3
"""
Generate new environment configuration from templates.

Usage:
    python generate_env.py <config_name>

Example:
    python generate_env.py AZURE_PG_DUAL

This creates configs/overlays/AZURE_PG_DUAL/ with:
- compose.yaml (overlay)
- env/dibbs-ecr-viewer.env
"""

import argparse
import os
import shutil
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate environment-specific configuration"
    )
    parser.add_argument(
        "config_name",
        help="Configuration name (e.g., AZURE_PG_DUAL, AWS_INTEGRATED). "
             "Also accepts underscore variants like AWS_INTEGRATED."
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing configuration if directory exists"
    )
    return parser.parse_args()


def main():
    args = parse_args()

    # Directories
    script_dir = Path(__file__).parent.resolve()
    base_dir = script_dir / ".." / "base"
    overlay_dir = script_dir / ".." / "overlays" / args.config_name

    print(f"Generating configuration for: {args.config_name}")
    print(f"Output directory: {overlay_dir}")

    if overlay_dir.exists():
        if args.force:
            print(f"WARNING: Overwriting existing directory: {overlay_dir}")
            # Only regenerate env file, don't recreate directory structure
        else:
            print(f"ERROR: Directory already exists: {overlay_dir}")
            return 1
    else:
        # Create overlay directory structure only if not exists
        (overlay_dir / "env").mkdir(parents=True)
        (overlay_dir / "overrides").mkdir(parents=True)

    # Copy base compose.yaml to overlay
    compose_source = base_dir / "compose.yaml"
    compose_target = overlay_dir / "compose.yaml"

    if compose_source.exists():
        shutil.copy(compose_source, compose_target)
        print(f"Copied: {compose_source} -> {compose_target}")
    else:
        # Create minimal overlay with just differences
        with open(compose_target, 'w') as f:
            f.write("# Overlay for ")  # Truncated line

    # Generate ecr-viewer.env based on config name pattern
    ecr_env = generate_ecr_viewer_env(args.config_name)
    (overlay_dir / "env" / "dibbs-ecr-viewer.env").write_text(ecr_env)
    print(f"Created: {overlay_dir / 'env' / 'dibbs-ecr-viewer.env'}")

    # Generate orchestration.env if different from base
    # Currently same as base, but this is where you'd add environment-specific values

    print("\nNext steps:")
    print("1. Review and update values in:")
    print(f"   {overlay_dir / 'env' / 'dibbs-ecr-viewer.env'}")
    print("2. Run with: docker-compose -f configs/base/compose.yaml -f configs/overlays/{config}/compose.yaml up")

    return 0


def generate_ecr_viewer_env(config_name):
    """Generate ecr-viewer.env content based on config name."""

    # Determine cloud type from config name
    config_upper = config_name.upper()

    if config_upper.startswith("AWS"):
        cloud_type = "aws"
    elif config_upper.startswith("AZURE"):
        cloud_type = "azure"
    elif config_upper.startswith("GCP"):
        cloud_type = "gcp"
    else:
        cloud_type = "unknown"

    # Check for dual vs integrated patterns
    is_dual = "_DUAL" in config_upper
    is_integrated = "INTEGRATED" in config_upper
    is_sqlserver = "SQLSERVER" in config_upper

    lines = [
        f"# Configuration: {config_name}",
        f"# Cloud Type: {cloud_type.upper()}",
        "# Generated by scripts/generate_env.py",
        "",
        f"CONFIG_NAME={config_name}",
        ""
    ]

    if cloud_type == "aws":
        lines.extend([
            "## AWS Configuration ##",
            "AWS_REGION=",
            "ECR_BUCKET_NAME=",
            "",
        ])
    elif cloud_type == "azure":
        lines.extend([
            "## Azure Configuration ##",
            "AZURE_STORAGE_CONNECTION_STRING=",
            "AZURE_CONTAINER_NAME=",
            "",
        ])
    elif cloud_type == "gcp":
        lines.extend([
            "## GCP Configuration ##",
            "GCP_CREDENTIALS=",
            "GCP_PROJECT_ID=",
            "",
        ])

    # Add shared configuration
    lines.extend([
        "## Shared Configuration ##",
        "NBS_API_PUB_KEY=",
        "NBS_PUB_KEY=",
        "",
    ])

    # Add database-specific fields for DUAL and NON_INTEGRATED environments
    if is_dual or is_integrated:
        if is_sqlserver:
            lines.extend([
                "## SQL Server Configuration ##",
                "SQL_SERVER_USER=",
                "SQL_SERVER_PASSWORD=",
                "SQL_SERVER_HOST=localhost",
                "",
            ])
        else:
            lines.extend([
                "## PostgreSQL Configuration ##",
                "DATABASE_URL=",
                "",
            ])
    elif is_integrated:
        # For INTEGRATED without DUAL, use DATABASE_URL
        if is_sqlserver:
            lines.extend([
                "## SQL Server Configuration ##",
                "SQL_SERVER_USER=",
                "SQL_SERVER_PASSWORD=",
                "SQL_SERVER_HOST=localhost",
                "",
            ])
        else:
            lines.extend([
                "## PostgreSQL Configuration ##",
                "DATABASE_URL=",
                "",
            ])

    # Add auth configuration for DUAL and NON_INTEGRATED environments
    if is_dual or is_integrated:
        lines.extend([
            "## Authentication Configuration ##",
            "AUTH_PROVIDER=ad",
            "AUTH_CLIENT_ID=",
            "AUTH_CLIENT_SECRET=",
            "AUTH_ISSUER=",
            "",
        ])

    lines.append('ORCHESTRATION_URL="http://dibbs-orchestration:8080"')

    return "\n".join(lines)


if __name__ == "__main__":
    exit(main())
